server:
  port: 9001
  
spring:
  application:
    name: spring-data-rest
    
  h2:
    console:
      enabled: true
      
  sql:
    init:
      platform: h2
      
      
  datasource:
    url: jdbc:h2:mem:mydb
    
  jpa:
    hibernate:
      ddl-auto: update